### ISSUE TITLE
Background Daemon

### ISSUE THREAD

**Issue by Thomas-Gelf** [Thomas-Gelf/icingaweb2-module-eventtracker#7]
## Tasks

* [x] Deal with issue expiration
* [x] Periodically sync SCOM issues
* [x] Periodically sync Icinga issues

## Requirements

* [x] Implement SystemD integration
* [x] Deal with DB failures
* [x] Detect DB config changes
